name: Linter

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        run: |
          docker pull thedoritos/unimgpicker:latest
          docker run --rm -v $PWD:/build -w /build thedoritos/unimgpicker make lint
